// examples/vue/src/pages/Point2DInput.vue
<script setup lang="ts">
/**
 * Point2DInput.vue — Custom Field Component for point2d type
 */
import { computed } from 'vue';
import { StandardFieldLayout } from '@formitiva/vue';
import type { DefinitionPropertyField, FieldValueType } from '@formitiva/vue';

const props = defineProps<{
  field: DefinitionPropertyField;
  value?: FieldValueType;
  error?: string;
  disabled?: boolean;
}>();

const emit = defineEmits<{
  change: [value: FieldValueType];
}>();

const xVal = computed(() => Array.isArray(props.value) ? String(props.value[0] ?? '') : '');
const yVal = computed(() => Array.isArray(props.value) ? String(props.value[1] ?? '') : '');

function emitUpdate(newX: string, newY: string) {
  emit('change', [newX, newY] as unknown as FieldValueType);
}
</script>

<template>
  <StandardFieldLayout :field="field" :error="error">
    <div class="point2d-inputs">
      <label>X:</label>
      <input
        type="number"
        :value="xVal"
        :disabled="disabled"
        @blur="(e) => emitUpdate((e.target as HTMLInputElement).value, yVal)"
      />
      <label>Y:</label>
      <input
        type="number"
        :value="yVal"
        :disabled="disabled"
        @blur="(e) => emitUpdate(xVal, (e.target as HTMLInputElement).value)"
      />
    </div>
  </StandardFieldLayout>
</template>

<style scoped>
.point2d-inputs {
  display: flex;
  align-items: center;
  gap: 8px;
  width: 100%;
}
.point2d-inputs label {
  font-size: 0.82rem;
  color: #666;
  min-width: 16px;
}
.point2d-inputs input {
  width: 90px;
  padding: 6px 8px;
  border: 1px solid #d0d5dd;
  border-radius: 6px;
  font-size: 0.9rem;
  outline: none;
  transition: border-color 0.15s;
}
.point2d-inputs input:focus {
  border-color: #6c63ff;
}
</style>

// examples/angular/src/app/pages/component/point2d-input.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import {
  BaseFieldComponent,
  StandardFieldLayoutComponent,
} from '@formitiva/angular';

export type Point2DValue = [string, string];

@Component({
  selector: 'app-point2d-input',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [StandardFieldLayoutComponent],
  styles: [`
    .point2d-inputs {
      display: flex;
      align-items: center;
      gap: 8px;
      width: 100%;
      min-width: 0;
    }
    .point2d-inputs label {
      font-size: 0.82rem;
      color: #666;
      min-width: 16px;
    }
    .point2d-inputs input {
      width: 90px;
      padding: 6px 8px;
      border: 1px solid #d0d5dd;
      border-radius: 6px;
      font-size: 0.9rem;
      outline: none;
      transition: border-color 0.15s;
    }
    .point2d-inputs input:focus {
      border-color: #6c63ff;
    }
  `],
  template: `
    <fv-standard-field-layout [field]="field" [error]="errorSig()">
      <div class="point2d-inputs">
        <label>X:</label>
        <input
          type="number"
          [value]="xVal"
          [disabled]="disabled"
          (input)="onXInput($event)"
          (blur)="onXBlur($event)"
        />
        <label>Y:</label>
        <input
          type="number"
          [value]="yVal"
          [disabled]="disabled"
          (input)="onYInput($event)"
          (blur)="onYBlur($event)"
        />
      </div>
    </fv-standard-field-layout>
  `,
})
export class Point2DInputComponent extends BaseFieldComponent<Point2DValue> {
  get xVal(): string {
    return Array.isArray(this.value) ? String(this.value[0] ?? '') : '';
  }

  get yVal(): string {
    return Array.isArray(this.value) ? String(this.value[1] ?? '') : '';
  }

  private emit(x: string, y: string, trigger: 'change' | 'blur' | 'sync'): void {
    const val: Point2DValue = [x, y];
    this.emitChange(val);
    this.updateError(this.doValidate(val, trigger));
  }

  onXInput(e: Event): void {
    this.emit((e.target as HTMLInputElement).value, this.yVal, 'change');
  }

  onXBlur(e: Event): void {
    this.emit((e.target as HTMLInputElement).value, this.yVal, 'blur');
  }

  onYInput(e: Event): void {
    this.emit(this.xVal, (e.target as HTMLInputElement).value, 'change');
  }

  onYBlur(e: Event): void {
    this.emit(this.xVal, (e.target as HTMLInputElement).value, 'blur');
  }
}
