// packages/react/src/components/fields/base/PopupOptionMenu.tsx
import * as React from "react";
import * as ReactDOM from "react-dom";

export type PopupOptionMenuPosition = {
  x: number;
  y: number;
}

export interface PopupOption {
  label: string;
}

export interface PopupOptionMenuProps<T extends PopupOption> {
  pos: PopupOptionMenuPosition | null;
  options: T[];
  onClose: () => void;
  onClickOption: (option: T) => void;
}

export function PopupOptionMenu<T extends PopupOption>({
  pos,
  options,
  onClose,
  onClickOption
}: PopupOptionMenuProps<T>) {
  const menuRef = React.useRef<HTMLDivElement>(null);
  const isSelectingRef = React.useRef<boolean>(false);
  const [adjustedPosition, setAdjustedPosition] = React.useState<{ top: number; left: number; ready: boolean }>({ 
    top: pos?.y ?? 0, 
    left: pos?.x ?? 0, 
    ready: false 
  });
  
  // Prefer an explicit `#popup-root` if present; otherwise render into document.body
  const popupRoot =
    typeof window !== "undefined"
      ? document.getElementById("popup-root") || document.body
      : null;
  
  React.useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      // If we're in the process of selecting an option, don't close
      if (isSelectingRef.current) {
        return;
      }

      const target = event.target as HTMLElement;

      // If the click is on a menu item by data attribute, ignore it.
      if (target.dataset?.popupMenu === "item") {
        return;
      }

      if (
        menuRef.current &&
        event.target instanceof Node &&
        !menuRef.current.contains(event.target)
      ) {
        onClose();
      }
    }
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, [onClose]);

  // Calculate adjusted position based on menu dimensions and viewport
  // Use useLayoutEffect to avoid visual flash
  React.useLayoutEffect(() => {
    if (!menuRef.current || !pos || pos.x == null || pos.y == null) {
      return;
    }

    const menuRect = menuRef.current.getBoundingClientRect();
    const vw = window.innerWidth;
    const vh = window.innerHeight;

    let left = pos.x;
    let top = pos.y;

    // Check if menu would overflow right edge
    if (left + menuRect.width > vw) {
      // Try to align to the right edge of viewport with some padding
      left = Math.max(0, vw - menuRect.width - 10);
    }

    // Check if menu would overflow bottom edge
    if (top + menuRect.height > vh) {
      // Flip to show above the trigger element
      // Assume the trigger has some height, subtract menu height and a small gap
      top = Math.max(0, pos.y - menuRect.height - 5);
    }

    setAdjustedPosition({ top, left, ready: true });
  }, [pos, options]);

  if (!popupRoot) return null;
  if (options === undefined || options.length === 0) return null;
  // allow 0 coordinates; only bail when pos or coordinates are null/undefined
  if (!pos || pos.x == null || pos.y == null) return null;

  return ReactDOM.createPortal(
    <div
      ref={menuRef}
      onMouseDown={(e) => {
        e.stopPropagation();
      }}
      style={{
        position: "fixed",
        top: adjustedPosition.top,
        left: adjustedPosition.left,
        visibility: adjustedPosition.ready ? "visible" : "hidden",
        backgroundColor: "var(--formitiva-primary-bg, #fff)",
        border: "1px solid var(--formitiva-border-color, #ccc)",
        borderRadius: "var(--formitiva-border-radius, 4px)",
        boxShadow: "var(--formitiva-shadow, 0 2px 10px rgba(0,0,0,0.2))",
        zIndex: 9999,
        minWidth: "var(--formitiva-menu-min-width, 150px)",
        maxHeight: "var(--formitiva-menu-max-height, 300px)",
        overflowY: "auto",
        pointerEvents: "auto",
      }}
    >
      {options.map((option: T, index: number) => (
        <div
          key={option.label ?? index}
          data-popup-menu="item"
          onMouseDown={(e) => {
            e.stopPropagation();
            isSelectingRef.current = true;
          }}
          onClick={(e) => {
            e.stopPropagation();
            e.preventDefault();
            onClickOption(option);
            onClose();
            // Reset flag after a small delay
            setTimeout(() => {
              isSelectingRef.current = false;
            }, 100);
          }}
          style={{
            padding: "var(--formitiva-menu-item-padding, 8px 12px)",
            cursor: "pointer",
            fontSize: "var(--formitiva-menu-item-font-size, 0.8em)",
            borderBottom: index < options.length - 1 ? "1px solid var(--formitiva-border-light, #eee)" : undefined,
            transition: "background-color 0.15s ease",
          }}
          onMouseEnter={(e) => {
            e.currentTarget.style.backgroundColor = "var(--formitiva-option-menu-hover-bg, #e0e0e0)";
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.backgroundColor = "transparent";
          }}
        >
          {option.label}
        </div>
      ))}
    </div>,
    popupRoot
  );
};

export default PopupOptionMenu;

// packages/angular/src/components/fields/base/popup-option-menu.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  Input,
  Output,
  EventEmitter,
  signal,
  ElementRef,
  ViewChild,
  HostListener,
  ChangeDetectorRef,
} from '@angular/core';
import type { OnChanges, SimpleChanges, AfterViewInit, OnDestroy } from '@angular/core';
import { NgIf, NgFor, NgStyle } from '@angular/common';

export interface PopupOption {
  label: string;
}

export type PopupOptionMenuPosition = { x: number; y: number };

@Component({
  selector: 'fv-popup-option-menu',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgIf, NgFor, NgStyle],
  template: `
    <div
      *ngIf="visible"
      #menuEl
      [ngStyle]="menuStyle"
      (mousedown)="$event.stopPropagation()"
    >
      <div
        *ngFor="let opt of options"
        data-popup-menu="item"
        [ngStyle]="itemStyle"
        (mousedown)="onSelect(opt)"
      >{{ opt.label }}</div>
    </div>
  `,
})
export class PopupOptionMenuComponent<T extends PopupOption> implements OnChanges, AfterViewInit, OnDestroy {
  @Input() pos: PopupOptionMenuPosition | null = null;
  @Input() options: T[] = [];
  @Output() closed = new EventEmitter<void>();
  @Output() optionClicked = new EventEmitter<T>();

  @ViewChild('menuEl') menuEl?: ElementRef<HTMLDivElement>;

  private attachedToBody = false;

  constructor(private cdr: ChangeDetectorRef) {}

  private adjustedTop = 0;
  private adjustedLeft = 0;
  private ready = false;
  private adjustedWidth: number | null = null;
  private adjustedMaxHeight: number | null = null;

  get visible(): boolean {
    return !!this.pos && this.options.length > 0;
  }

  get menuStyle(): Record<string, string> {
    const style: Record<string, string> = {
      position: 'fixed',
      top: `${this.adjustedTop}px`,
      left: `${this.adjustedLeft}px`,
      visibility: this.ready ? 'visible' : 'hidden',
      backgroundColor: 'var(--formitiva-primary-bg, #fff)',
      border: '1px solid var(--formitiva-border-color, #ccc)',
      borderRadius: 'var(--formitiva-border-radius, 4px)',
      boxShadow: 'var(--formitiva-shadow, 0 2px 10px rgba(0,0,0,0.2))',
      zIndex: '9999',
      overflowY: 'auto',
      pointerEvents: 'auto',
      boxSizing: 'border-box',
    };

    if (this.adjustedWidth != null) {
      style['width'] = `${this.adjustedWidth}px`;
    } else {
      style['minWidth'] = 'var(--formitiva-menu-min-width, 150px)';
    }

    if (this.adjustedMaxHeight != null) {
      style['maxHeight'] = `${this.adjustedMaxHeight}px`;
    } else {
      style['maxHeight'] = 'var(--formitiva-menu-max-height, 300px)';
    }

    return style;
  }

  itemStyle = {
    padding: '8px 12px',
    cursor: 'pointer',
    fontSize: '0.95em',
  };

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['pos'] && this.pos) {
      this.adjustedTop = this.pos.y;
      this.adjustedLeft = this.pos.x;
      this.ready = false;
      // adjust after next render cycle
      setTimeout(() => this.adjustPosition(), 0);
    }
  }

  private adjustPosition(): void {
    if (!this.menuEl || !this.pos) return;

    const el = this.menuEl.nativeElement;

    // Move menu element to document.body to avoid being clipped by transformed parents
    if (!this.attachedToBody && el.parentElement !== document.body) {
      document.body.appendChild(el);
      this.attachedToBody = true;
    }

    const margin = 10; // keep a small gap from viewport edges

    // Measure initial size
    let rect = el.getBoundingClientRect();
    const desiredWidth = rect.width;
    const desiredHeight = rect.height;

    const availableRight = Math.max(0, window.innerWidth - this.pos.x - margin);
    const availableLeft = Math.max(0, this.pos.x - margin);

    let left = this.pos.x;
    // If it fits to the right, keep it
    if (desiredWidth <= availableRight) {
      this.adjustedWidth = null;
      left = this.pos.x;
    } else if (desiredWidth <= availableRight + availableLeft) {
      // shift left so it fits within viewport
      const shift = desiredWidth - availableRight;
      left = Math.max(margin, this.pos.x - shift);
      this.adjustedWidth = null;
    } else {
      // cannot fit at full width, clamp width to viewport and pin to left margin
      this.adjustedWidth = Math.max(100, window.innerWidth - margin * 2);
      left = margin;
      // apply width immediately so we can re-measure height
      try { el.style.width = `${this.adjustedWidth}px`; } catch (_) {}
      rect = el.getBoundingClientRect();
    }

    // Vertical placement: try below, then shift up, else clamp height
    const availableBottom = Math.max(0, window.innerHeight - this.pos.y - margin);
    const availableTop = Math.max(0, this.pos.y - margin);

    let top = this.pos.y;
    if (rect.height <= availableBottom) {
      this.adjustedMaxHeight = null;
      top = this.pos.y;
    } else if (rect.height <= availableBottom + availableTop) {
      const shiftY = rect.height - availableBottom;
      top = Math.max(margin, this.pos.y - shiftY);
      this.adjustedMaxHeight = null;
    } else {
      // cannot fit vertically, pin to top margin and clamp maxHeight
      top = margin;
      this.adjustedMaxHeight = Math.max(80, window.innerHeight - margin * 2);
    }

    this.adjustedTop = top;
    this.adjustedLeft = left;
    this.ready = true;

    // Ensure view updates immediately
    try { this.cdr.detectChanges(); } catch (_) {}
  }

  onSelect(opt: T): void {
    this.optionClicked.emit(opt);
    this.closed.emit();
  }

  @HostListener('document:mousedown', ['$event'])
  onDocumentClick(event: MouseEvent): void {
    const target = event.target as HTMLElement;
    if (target.dataset?.['popupMenu'] === 'item') return;
    if (this.menuEl?.nativeElement.contains(target)) return;
    this.closed.emit();
  }

  ngAfterViewInit(): void {
    // noop — actual DOM relocation happens in adjustPosition
  }

  ngOnDestroy(): void {
    // If the menu element was moved to body, remove it to avoid orphan nodes
    try {
      if (this.attachedToBody && this.menuEl && this.menuEl.nativeElement.parentElement === document.body) {
        document.body.removeChild(this.menuEl.nativeElement);
      }
    } catch (_) {
      // ignore
    }
  }
}
