// examples/vue/src/App.vue
<script setup lang="ts">
import { RouterLink, RouterView } from 'vue-router';

const navItems = [
  { path: '/basic',            label: 'Basic / Quick Start',   description: 'Contact form with inline submit' },
  { path: '/themes',           label: 'Theme Demo',            description: 'Preview and switch themes' },
  { path: '/groups',           label: 'Field Groups',           description: 'Organize fields into collapsible groups' },
  { path: '/parents',          label: 'Conditional Fields',     description: 'Show/hide fields based on other values' },
  { path: '/validation',       label: 'Form Validation',        description: 'Cross-field validation handler via plugin' },
  { path: '/submit-handler',   label: 'Submit Handler',         description: 'Named submission handler via plugin' },
  { path: '/translation',      label: 'Translation / i18n',     description: 'Switch language at runtime' },
  { path: '/component',        label: 'Component',              description: 'Custom Point2D field component via plugin' },
  { path: '/visibility',     label: 'Visibility Handler',     description: 'Show/hide/disable fields via registered handlers' },
  { path: '/computed-values', label: 'Computed Values',        description: 'Derive field values from other fields (e.g. total = qty × price)' },
  { path: '/layout-nav',      label: 'Layout - Nav',           description: 'Left-side navigation panel splits form into sections' },
  { path: '/layout-tab',      label: 'Layout - Tab',           description: 'Tab buttons above the form split fields into sections' },
  { path: '/layout-wizard',   label: 'Layout - Wizard',        description: 'Multi-step wizard with Previous / Next navigation' },
];
</script>

<template>
  <div class="shell">
    <aside class="sidebar">
      <div class="sidebar-header">
        <h1>@formitiva/vue</h1>
        <p>Example application</p>
      </div>
      <nav>
        <RouterLink
          v-for="item in navItems"
          :key="item.path"
          :to="item.path"
          class="nav-link"
          active-class="active"
        >
          {{ item.label }}
          <span class="nav-desc">{{ item.description }}</span>
        </RouterLink>
      </nav>
    </aside>
    <main class="main">
      <RouterView />
    </main>
  </div>
</template>

<style>
.shell { display: flex; min-height: 100vh; }

.sidebar {
  width: 240px; min-width: 240px;
  background: #1e1e2e; color: #cdd6f4;
  display: flex; flex-direction: column;
}

.sidebar-header {
  padding: 24px 20px 16px;
  border-bottom: 1px solid rgba(255,255,255,0.08);
}

.sidebar-header h1 {
  margin: 0 0 4px; font-size: 1rem; font-weight: 700;
  color: #cba6f7; letter-spacing: 0.02em;
}

.sidebar-header p { margin: 0; font-size: 0.75rem; color: #6c7086; }

nav { flex: 1; padding: 12px 0; overflow-y: auto; }

.nav-link {
  display: flex; flex-direction: column;
  padding: 10px 20px; color: #a6adc8;
  text-decoration: none; font-size: 0.86rem;
  border-left: 3px solid transparent;
  transition: all 0.15s ease; line-height: 1.3;
}
.nav-link:hover { background: rgba(255,255,255,0.05); color: #cdd6f4; }
.nav-link.active { border-left-color: #cba6f7; background: rgba(203,166,247,0.1); color: #cba6f7; }

.nav-desc { font-size: 0.72rem; color: #585b70; margin-top: 2px; }
.nav-link.active .nav-desc { color: #9399b2; }

.main { flex: 1; overflow-y: auto; background: #f5f6f8; }
</style>

// examples/react/src/App.tsx
import { NavLink, Route, Routes } from 'react-router-dom';
import Home from './pages/Home';
import Themes from './pages/Themes';
import Groups from './pages/Groups';
import Parents from './pages/Parents';
import Validation from './pages/Validation';
import SubmitHandler from './pages/SubmitHandler';
import Translation from './pages/Translation';
import ComponentDemo from './pages/Component';
import Visibility from './pages/Visibility';
import ComputedValues from './pages/ComputedValues';
import LayoutNav from './pages/LayoutNav';
import LayoutTab from './pages/LayoutTab';
import LayoutWizard from './pages/LayoutWizard';

const navItems = [
  { path: '/basic',            label: 'Basic / Quick Start',   description: 'Contact form with inline submit' },
  { path: '/themes',           label: 'Theme Demo',            description: 'Preview and switch themes' },
  { path: '/groups',           label: 'Field Groups',           description: 'Organize fields into collapsible groups' },
  { path: '/parents',          label: 'Conditional Fields',     description: 'Show/hide fields based on other values' },
  { path: '/validation',       label: 'Form Validation',        description: 'Cross-field validation handler via plugin' },
  { path: '/submit-handler',   label: 'Submit Handler',         description: 'Named submission handler via plugin' },
  { path: '/translation',      label: 'Translation / i18n',     description: 'Switch language at runtime' },
  { path: '/component',        label: 'Component',              description: 'Custom Point2D field component via plugin' },
  { path: '/visibility',     label: 'Visibility Handler',     description: 'Show/hide/disable fields via registered handlers' },
  { path: '/computed-values', label: 'Computed Values',        description: 'Derive field values from other fields (e.g. total = qty × price)' },
  { path: '/layout-nav',      label: 'Layout - Nav',           description: 'Left-side navigation panel splits form into sections' },
  { path: '/layout-tab',      label: 'Layout - Tab',           description: 'Tab buttons above the form split fields into sections' },
  { path: '/layout-wizard',   label: 'Layout - Wizard',        description: 'Multi-step wizard with Previous / Next navigation' },
];

export default function App() {
  return (
    <div style={styles.shell}>
      <aside style={styles.sidebar}>
        <div style={styles.sidebarHeader}>
          <h1 style={styles.sidebarTitle}>@formitiva/react</h1>
          <p style={styles.sidebarSubtitle}>Example application</p>
        </div>
        <nav style={styles.nav}>
          {navItems.map((item) => (
            <NavLink
              key={item.path}
              to={item.path}
              style={({ isActive }) => ({
                ...styles.navLink,
                ...(isActive ? styles.navLinkActive : {}),
              })}
            >
              {item.label}
              <span style={styles.navDesc}>{item.description}</span>
            </NavLink>
          ))}
        </nav>
      </aside>
      <main style={styles.main}>
        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="/basic" element={<Home />} />
          <Route path="/groups" element={<Groups />} />
          <Route path="/parents" element={<Parents />} />
          <Route path="/validation" element={<Validation />} />
          <Route path="/submit-handler" element={<SubmitHandler />} />
          <Route path="/translation" element={<Translation />} />
          <Route path="/component" element={<ComponentDemo />} />
          <Route path="/visibility" element={<Visibility />} />
          <Route path="/computed-values" element={<ComputedValues />} />
          <Route path="/themes" element={<Themes />} />
          <Route path="/layout-nav" element={<LayoutNav />} />
          <Route path="/layout-tab" element={<LayoutTab />} />
          <Route path="/layout-wizard" element={<LayoutWizard />} />
        </Routes>
      </main>
    </div>
  );
}

const styles: Record<string, React.CSSProperties> = {
  shell: { display: 'flex', minHeight: '100vh' },
  sidebar: {
    width: 240, minWidth: 240,
    background: '#1e1e2e', color: '#cdd6f4',
    display: 'flex', flexDirection: 'column',
  },
  sidebarHeader: {
    padding: '24px 20px 16px',
    borderBottom: '1px solid rgba(255,255,255,0.08)',
  },
  sidebarTitle: {
    margin: '0 0 4px', fontSize: '1rem', fontWeight: 700,
    color: '#cba6f7', letterSpacing: '0.02em',
  },
  sidebarSubtitle: { margin: 0, fontSize: '0.75rem', color: '#6c7086' },
  nav: { flex: 1, padding: '12px 0', overflowY: 'auto' },
  navLink: {
    display: 'flex', flexDirection: 'column',
    padding: '10px 20px', color: '#a6adc8',
    textDecoration: 'none', fontSize: '0.86rem',
    borderLeft: '3px solid transparent',
    transition: 'all 0.15s ease', lineHeight: 1.3,
  },
  navLinkActive: {
    borderLeftColor: '#cba6f7',
    background: 'rgba(203, 166, 247, 0.1)',
    color: '#cba6f7',
  },
  navDesc: { fontSize: '0.72rem', color: '#585b70', marginTop: 2 },
  main: { flex: 1, overflowY: 'auto', background: '#f5f6f8' },
};
