// packages/angular/src/components/layout/field-group.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  Input,
  signal,
  inject,
} from '@angular/core';
import { NgIf, NgFor } from '@angular/common';
import type { DefinitionPropertyField, FieldValueType, ErrorType } from '@formitiva/core';
import { FieldRendererComponent } from './field-renderer.component';
import { FormitivaContextService } from '../../services/formitiva-context.service';

@Component({
  selector: 'fv-field-group',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgIf, NgFor, FieldRendererComponent],
  template: `
    <fieldset class="formitiva-group">
      <legend (click)="toggle()" class="formitiva-group_legend">
        <span>{{ ctx.t()(groupName) }}</span>
        <span class="formitiva-group_legend_arrow">{{ isOpen() ? '▼' : '▶' }}</span>
      </legend>
      <ng-container *ngIf="isOpen()">
        <fv-field-renderer
          *ngFor="let field of fields; trackBy: trackByName"
          [field]="field"
          [valuesMap]="valuesMap"
          [handleChange]="handleChange"
          [handleError]="handleError"
          [errorsMap]="errorsMap"
          [disabledByRef]="disabledByRef"
        ></fv-field-renderer>
      </ng-container>
    </fieldset>
  `,
})
export class FieldGroupComponent {
  @Input({ required: true }) groupName!: string;
  @Input() defaultOpen = true;
  @Input({ required: true }) fields!: DefinitionPropertyField[];
  @Input({ required: true }) valuesMap!: Record<string, FieldValueType>;
  @Input({ required: true }) handleChange!: (name: string, value: FieldValueType) => void;
  @Input() handleError?: (name: string, error: ErrorType) => void;
  @Input() errorsMap?: Record<string, string>;
  @Input() disabledByRef?: Record<string, boolean>;

  readonly ctx = inject(FormitivaContextService);
  readonly isOpen = signal(true);

  toggle(): void {
    this.isOpen.update(v => !v);
  }

  trackByName(_: number, f: DefinitionPropertyField): string {
    return f.name;
  }
}

// packages/vue/src/components/layout/FieldGroup.vue
<script setup lang="ts">
import { ref } from 'vue';
import type { DefinitionPropertyField, FieldValueType, ErrorType } from '@formitiva/core';
import FieldRenderer from "./FieldRenderer.vue";

export interface FieldGroupProps {
  groupName: string;
  defaultOpen?: boolean;
  fields: DefinitionPropertyField[];
  valuesMap: Record<string, FieldValueType>;
  handleChange: (fieldName: string, value: FieldValueType) => void;
  handleError?: (fieldName: string, error: ErrorType) => void;
  errorsMap?: Record<string, string>;
  t: (key: string) => string;
  disabledByRef?: Record<string, boolean>;
}

const props = withDefaults(defineProps<FieldGroupProps>(), {
  defaultOpen: true
});

const isOpen = ref(props.defaultOpen);
const onToggle = () => { isOpen.value = !isOpen.value; };
</script>

<template>
  <fieldset class="formitiva-group">
    <legend @click="onToggle" class="formitiva-group_legend">
      <span>{{ t(groupName) }}</span>
      <span class="formitiva-group_legend_arrow">{{ isOpen ? "\u25BC" : "\u25B6" }}</span>
    </legend>
    <template v-if="isOpen">
      <FieldRenderer
        v-for="field in fields"
        :key="field.name"
        :field="field"
        :valuesMap="valuesMap"
        :handleChange="handleChange"
        :handleError="handleError"
        :errorsMap="errorsMap"
        :disabled-by-ref="disabledByRef"
      />
    </template>
  </fieldset>
</template>
