// packages/vue/src/components/fields/text-numeric/FloatArrayInput.vue
<script setup lang="ts">
import { computed } from 'vue';
import { StandardFieldLayout } from "../../layout/LayoutComponents";
import type { DefinitionPropertyField, BaseInputProps } from '@formitiva/core';
import { CSS_CLASSES, combineClasses } from '@formitiva/core';
import { useFieldValidator } from "../../../hooks/useFieldValidator";
import { useUncontrolledValidatedInput } from "../../../hooks/useUncontrolledValidatedInput";

export type FloatArrayInputProps = BaseInputProps<string | number[], DefinitionPropertyField>;

const props = defineProps<FloatArrayInputProps>();

const emit = defineEmits<{
  change: [value: string | number[]];
  error: [error: string | null];
}>();

const validate = useFieldValidator(props.field, props.error);

const stringValue = computed(() => 
  Array.isArray(props.value) ? props.value.join(", ") : String(props.value ?? "")
);

const { inputRef, error, handleChange, handleBlur } = useUncontrolledValidatedInput({
  value: stringValue.value,
  onChange: (val: string) => emit('change', val),
  onError: (err: string | null) => emit('error', err),
  validate,
});
</script>

<template>
  <StandardFieldLayout :field="field" :error="error">
    <input
      :id="field.name"
      type="text"
      :defaultValue="stringValue"
      :ref="inputRef"
      @input="handleChange"
      @blur="handleBlur"
      :class="combineClasses(CSS_CLASSES.input, CSS_CLASSES.textInput)"
      style="flex: 1"
      :aria-invalid="!!error"
      :aria-describedby="error ? `${field.name}-error` : undefined"
    />
  </StandardFieldLayout>
</template>

// packages/react/src/components/fields/text-numeric/FloatArrayInput.tsx
// components/FloatArrayInput.tsx
import * as React from "react";
import { StandardFieldLayout } from "../../layout/LayoutComponents";
import type {
  DefinitionPropertyField,
  BaseInputProps,
} from '@formitiva/core';
import { CSS_CLASSES, combineClasses } from '@formitiva/core';
import { useFieldValidator } from "../../../hooks/useFieldValidator";
import { useUncontrolledValidatedInput } from "../../../hooks/useUncontrolledValidatedInput";

// Props for the generic number array input
export type FloatArrayInputProps = BaseInputProps<
  string | number[],
  DefinitionPropertyField
>;

/**
 * FloatArrayInput component
 */

const FloatArrayInput: React.FC<FloatArrayInputProps> = ({
  field,
  value,
  onChange,
  onError,
  error: externalError,
}) => {
  const validate = useFieldValidator(field, externalError);

  const stringValue = Array.isArray(value) ? value.join(", ") : String(value ?? "");

  const { inputRef, error, handleChange } = useUncontrolledValidatedInput<HTMLInputElement, string>({
    value: stringValue,
    onChange,
    onError,
    validate,
  });

  return (
    <StandardFieldLayout field={field} error={error}>
      <input
        id={field.name}
        type="text"
        defaultValue={stringValue}
        ref={inputRef}
        onChange={handleChange}
        className={combineClasses(CSS_CLASSES.input, CSS_CLASSES.textInput)}
        style={{ flex: 1 }}
        aria-invalid={!!error}
        aria-describedby={error ? `${field.name}-error` : undefined}
      />
    </StandardFieldLayout>
  );
};

FloatArrayInput.displayName = "FloatArrayInput";
export default React.memo(FloatArrayInput);
