// packages/react/src/components/layout/LayoutComponents.tsx
import * as React from "react";
import useFormitivaContext from "../../hooks/useFormitivaContext";
import { combineClasses, CSS_CLASSES } from '@formitiva/core';
import Tooltip from "../fields/base/Tooltip";
import type { DefinitionPropertyField } from '@formitiva/core';

const TooltipMemo = React.memo(Tooltip);

/**
 * ColumnFieldLayout - Vertical layout wrapper for form fields
 * 
 * This component provides a column-based layout pattern:
 * - Label on top (left-aligned or center-aligned based on labelLayout)
 * - Value/input area below
 * - Optional tooltip support
 * - Error display area
 * 
 * Usage:
 * <ColumnFieldLayout field={field} error={error}>
 *   <textarea ... />
 * </ColumnFieldLayout>
 */
export const ColumnFieldLayout = React.memo(({
  field,
  error,
  children,
  showLabel = true,
}: {
  field: DefinitionPropertyField;
  error?: string | null;
  children: React.ReactNode;
  showLabel?: boolean;
}) => {
  const { t } = useFormitivaContext();

  // Determine label alignment based on labelLayout
  const labelAlignment = field.labelLayout === 'column-center' ? 'center' : 'left';

  const rootStyle = React.useMemo<React.CSSProperties>(() => {
    const s: React.CSSProperties = {
      display: 'flex',
      flexDirection: 'column',
      gap: 'var(--formitiva-label-gap, 4px)',
    };
    (s as Record<string, string>)['--label-align'] = labelAlignment;
    return s;
  }, [labelAlignment]);

  const labelStyle = React.useMemo<React.CSSProperties>(() => ({
    textAlign: labelAlignment as 'left' | 'center',
    width: '100%',
    minWidth: 'unset',
    display: 'block',
    marginBottom: '10px',
  }), [labelAlignment]);

  const rowStyle = React.useMemo<React.CSSProperties>(() => ({
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--formitiva-inline-gap, 8px)',
    width: '100%',
  }), []);

  return (
    <div className={`${CSS_CLASSES.field} column-layout`} style={rootStyle}>
      {showLabel && (
        <label
          id={`${field.name}-label`}
          className={CSS_CLASSES.label}
          htmlFor={field.name}
          style={labelStyle}
        >
          {t(field.displayName)}
        </label>
      )}

      <div style={rowStyle}>
        <div style={{ flex: 1, minWidth: 0 }}>
          {children}
        </div>
        {field.tooltip && <TooltipMemo content={field.tooltip} />}
      </div>

      {error && <ErrorDiv id={`${field.name}-error`}>{error}</ErrorDiv>}
    </div>
  );
});

ColumnFieldLayout.displayName = 'ColumnFieldLayout';

/**
 * RowFieldLayout - Horizontal layout wrapper for form fields
 * 
 * This component provides the traditional two-column layout pattern:
 * - Label on the left using CSS_CLASSES.label
 * - Value/input area on the right
 * - Optional tooltip support
 * - Error display area
 * 
 * Usage:
 * <RowFieldLayout field={field} error={error}>
 *   <input ... />
 * </RowFieldLayout>
 */
export const RowFieldLayout = React.memo(({
  field,
  error,
  children,
  rightAlign = false,
}: {
  field: DefinitionPropertyField;
  error?: string | null;
  children: React.ReactNode;
  rightAlign?: boolean;
}) => {
  const { t } = useFormitivaContext();

  return (
    <div className={`${CSS_CLASSES.field} row-layout`}>
      <label
        id={`${field.name}-label`}
        className={CSS_CLASSES.label}
        htmlFor={field.name}
        style={{ textAlign: 'left' }}
      >
        {t(field.displayName)}
      </label>
      <div style={{ display: 'flex', flexDirection: 'column', flex: 1 }}>
        <div style={{ display: 'flex', alignItems: 'center', width: '100%' }}>
          <div style={{ flex: 1, display: 'flex', alignItems: 'center' }}>
            {rightAlign ? (
              <div style={{ display: 'flex', width: '100%', justifyContent: 'flex-end' }}>
                {children}
              </div>
            ) : (
              // left/center: children are rendered in the left flexible area; if the child itself centers
              // horizontally it should do so using its own wrapper (Button does this for 'center').
              <div style={{ display: 'flex', width: '100%', justifyContent: 'flex-start' }}>{children}</div>
            )}
          </div>

          {field.tooltip && (
            <div style={{ marginLeft: 8, display: 'flex', alignItems: 'center' }}>
              <TooltipMemo content={field.tooltip} />
            </div>
          )}
        </div>

        {error && <ErrorDiv id={`${field.name}-error`}>{error}</ErrorDiv>}
      </div>
    </div>
  );
});

RowFieldLayout.displayName = 'RowFieldLayout';

/**
 * StandardFieldLayout - Smart layout wrapper that delegates to appropriate layout component
 * 
 * This component automatically chooses between row and column layouts based on field.labelLayout:
 * - Uses ColumnFieldLayout when field.labelLayout === 'column'
 * - Uses RowFieldLayout for default/row layout
 * - Maintains consistent API for all field components
 * 
 * Usage:
 * <StandardFieldLayout field={field} error={error}>
 *   <input ... />
 * </StandardFieldLayout>
 */
export const StandardFieldLayout = React.memo(({
  field,
  error,
  children,
  rightAlign = false,
}: {
  field: DefinitionPropertyField;
  error?: string | null;
  children: React.ReactNode;
  rightAlign?: boolean; // For checkbox, switch, etc.
}) => {
  // Use column layout if explicitly specified
  if (field.labelLayout === 'column-left' || field.labelLayout === 'column-center') {
    // For column layout, always show label
    return (
      <ColumnFieldLayout field={field} error={error} showLabel>
        {children}
      </ColumnFieldLayout>
    );
  }

  if (field.type === 'checkbox' || field.type === 'switch') {
    // For checkbox and switch, omit label in column layout
    return (
      <ColumnFieldLayout field={field} error={error} showLabel={false}>
        {children}
      </ColumnFieldLayout>
    );
  }

  // Default to row layout: 2 grid columns label + value
  return (
    <RowFieldLayout field={field} error={error} rightAlign={rightAlign}>
      {children}
    </RowFieldLayout>
  );
});

StandardFieldLayout.displayName = 'StandardFieldLayout';

export const ErrorDiv = React.memo(({ children, id }: { children: React.ReactNode; id?: string }) => {
  const style = React.useMemo<React.CSSProperties>(() => ({
    color: 'var(--formitiva-error-color, red)',
    fontSize: '13px',
    marginTop: '4px',
    fontWeight: 'var(--formitiva-font-weight)',
    display: "flex",
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "flex-start",
    userSelect: "none",
  }), []);

  return <div id={id} style={style}>{children}</div>;
});

ErrorDiv.displayName = 'ErrorDiv';

/**
 * InstanceName - display and edit an instance name in a compact grid row
 *                on top of fields list
 *
 * Props:
 * - `name`: current instance name
 * - `onChange`: callback invoked with new name when edited
 */
export const InstanceName = React.memo(({ name, onChange }: { name: string; onChange: (n: string) => void }) => {
  const { t } = useFormitivaContext();

  return (
    <div style={{ marginBottom: 16 }}>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: 12, alignItems: 'center' }}>
        <label
          htmlFor="instance-name-input"
          style={{
            margin: 0,
            fontSize: '0.95em',
            fontWeight: 500,
            color: 'var(--formitiva-text-color, #333)'
          }}
        >
          {t('Instance Name')}
        </label>
        <input
          id="instance-name-input"
          type="text"
          value={name}
          className={combineClasses(CSS_CLASSES.input, CSS_CLASSES.textInput)}
          onChange={(e) => onChange(e.target.value)}
          placeholder={t('Enter instance name')}
        />
      </div>
      <div style={{ height: '1px', backgroundColor: 'var(--formitiva-separator, #e6e6e6)', marginTop: 12, marginBottom: 12 }} />
    </div>
  );
});

InstanceName.displayName = 'InstanceName';

// packages/angular/src/components/layout/layout-components.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  Input,
  inject,
} from '@angular/core';
import { NgIf, NgStyle } from '@angular/common';
import { CSS_CLASSES } from '@formitiva/core';
import { FormitivaContextService } from '../../services/formitiva-context.service';
import type { DefinitionPropertyField } from '@formitiva/core';
import { TooltipComponent } from '../fields/base/tooltip.component';

/**
 * ErrorDiv - displays a field-level error message
 */
@Component({
  selector: 'fv-error-div',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div [id]="id" [ngStyle]="style"><ng-content></ng-content></div>
  `,
  imports: [NgStyle],
})
export class ErrorDivComponent {
  @Input() id?: string;
  style = {
    color: 'var(--formitiva-error-color, red)',
    fontSize: '13px',
    marginTop: '4px',
    fontWeight: 'var(--formitiva-font-weight)',
    display: 'flex',
    flex: '1',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    userSelect: 'none',
  };
}

/**
 * ColumnFieldLayout - vertical label-above layout
 */
@Component({
  selector: 'fv-column-field-layout',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  styles: [':host { display:block; width:100%; }'],
  imports: [NgIf, NgStyle, ErrorDivComponent, TooltipComponent],
  template: `
    <div [class]="fieldClass" [ngStyle]="rootStyle">
      <label
        *ngIf="showLabel"
        [id]="field.name + '-label'"
        [class]="labelClass"
        [attr.for]="field.name"
        [ngStyle]="labelStyle"
      >{{ ctx.t()(field.displayName) }}</label>
      <div [ngStyle]="rowStyle">
        <div style="flex:1;min-width:0">
          <ng-content></ng-content>
        </div>
        <fv-tooltip *ngIf="field.tooltip" [content]="field.tooltip"></fv-tooltip>
      </div>
      <fv-error-div *ngIf="error" [id]="field.name + '-error'">{{ error }}</fv-error-div>
    </div>
  `,
})
export class ColumnFieldLayoutComponent {
  @Input({ required: true }) field!: DefinitionPropertyField;
  @Input() error?: string | null;
  @Input() showLabel = true;

  readonly ctx = inject(FormitivaContextService);

  get labelAlignment(): 'center' | 'left' {
    return this.field.labelLayout === 'column-center' ? 'center' : 'left';
  }

  get fieldClass() { return `${CSS_CLASSES.field} column-layout`; }
  get labelClass() { return CSS_CLASSES.label; }

  get rootStyle() {
    return {
      display: 'flex',
      flexDirection: 'column',
      width: '100%',
      gap: 'var(--formitiva-label-gap, 4px)',
    };
  }

  get labelStyle() {
    return {
      textAlign: this.labelAlignment,
      width: '100%',
      minWidth: 'unset',
      display: 'block',
      marginBottom: '10px',
    };
  }

  rowStyle = {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--formitiva-inline-gap, 8px)',
    width: '100%',
  };
}

/**
 * RowFieldLayout - horizontal label-left layout
 */
@Component({
  selector: 'fv-row-field-layout',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  styles: [':host { display:block; width:100%; }'],
  imports: [NgIf, ErrorDivComponent, TooltipComponent],
  template: `
    <div [class]="fieldClass">
      <label
        [id]="field.name + '-label'"
        [class]="labelClass"
        [attr.for]="field.name"
        style="text-align:left"
      >{{ ctx.t()(field.displayName) }}</label>
      <div style="display:flex;flex-direction:column;flex:1;min-width:0">
        <div style="display:flex;align-items:center;width:100%">
          <div style="flex:1;display:flex;align-items:center;min-width:0">
            <div [style.justifyContent]="rightAlign ? 'flex-end' : 'flex-start'"
                 style="display:flex;width:100%;min-width:0">
              <ng-content></ng-content>
            </div>
          </div>
          <div *ngIf="field.tooltip" style="margin-left:8px;display:flex;align-items:center">
            <fv-tooltip [content]="field.tooltip"></fv-tooltip>
          </div>
        </div>
        <fv-error-div *ngIf="error" [id]="field.name + '-error'">{{ error }}</fv-error-div>
      </div>
    </div>
  `,
})
export class RowFieldLayoutComponent {
  @Input({ required: true }) field!: DefinitionPropertyField;
  @Input() error?: string | null;
  @Input() rightAlign = false;

  readonly ctx = inject(FormitivaContextService);

  get fieldClass() { return CSS_CLASSES.field; }
  get labelClass() { return CSS_CLASSES.label; }
}

/**
 * StandardFieldLayout - renders row or column layout with a single projection slot
 */
@Component({
  selector: 'fv-standard-field-layout',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  styles: [':host { display:block; width:100%; }'],
  imports: [NgIf, NgStyle, ErrorDivComponent, TooltipComponent],
  template: `
    <div [class]="fieldClass" [ngStyle]="rootStyle">
      <label
        *ngIf="showLabel"
        [id]="field.name + '-label'"
        [class]="labelClass"
        [attr.for]="field.name"
        [ngStyle]="labelStyle"
      >{{ ctx.t()(field.displayName) }}</label>

      <div [ngStyle]="contentColumnStyle">
        <div [ngStyle]="contentRowStyle">
          <div [ngStyle]="contentInnerStyle">
            <div [ngStyle]="controlWrapperStyle">
              <ng-content></ng-content>
            </div>
          </div>
          <div *ngIf="field.tooltip" [ngStyle]="tooltipStyle">
            <fv-tooltip [content]="field.tooltip"></fv-tooltip>
          </div>
        </div>
        <fv-error-div *ngIf="error" [id]="field.name + '-error'">{{ error }}</fv-error-div>
      </div>
    </div>
  `,
})
export class StandardFieldLayoutComponent {
  @Input({ required: true }) field!: DefinitionPropertyField;
  @Input() error?: string | null;
  @Input() rightAlign = false;

  readonly ctx = inject(FormitivaContextService);

  get fieldClass(): string {
    return this.useColumn ? `${CSS_CLASSES.field} column-layout` : CSS_CLASSES.field;
  }

  get labelClass(): string {
    return CSS_CLASSES.label;
  }

  get useColumn(): boolean {
    return (
      this.field.labelLayout === 'column-left' ||
      this.field.labelLayout === 'column-center' ||
      this.field.type === 'checkbox' ||
      this.field.type === 'switch'
    );
  }

  get showLabelInColumn(): boolean {
    return this.field.type !== 'checkbox' && this.field.type !== 'switch';
  }

  get showLabel(): boolean {
    return this.useColumn ? this.showLabelInColumn : true;
  }

  get rootStyle(): Record<string, string> | null {
    if (!this.useColumn) return null;
    return {
      display: 'flex',
      flexDirection: 'column',
      width: '100%',
      gap: 'var(--formitiva-label-gap, 4px)',
    };
  }

  get labelStyle(): Record<string, string> | null {
    if (!this.useColumn) {
      return { textAlign: 'left' };
    }
    return {
      textAlign: this.field.labelLayout === 'column-center' ? 'center' : 'left',
      width: '100%',
      minWidth: 'unset',
      display: 'block',
      marginBottom: '10px',
    };
  }

  get contentColumnStyle(): Record<string, string> {
    return {
      display: 'flex',
      flexDirection: 'column',
      flex: this.useColumn ? '0 0 auto' : '1',
      width: '100%',
      minWidth: '0',
    };
  }

  get contentRowStyle(): Record<string, string> {
    return {
      display: 'flex',
      alignItems: 'center',
      gap: this.useColumn ? 'var(--formitiva-inline-gap, 8px)' : '0',
      width: '100%',
    };
  }

  get contentInnerStyle(): Record<string, string> {
    return {
      flex: '1',
      display: 'flex',
      alignItems: this.useColumn ? 'stretch' : 'center',
      minWidth: '0',
    };
  }

  get controlWrapperStyle(): Record<string, string> {
    if (this.useColumn) {
      return {
        width: '100%',
        minWidth: '0',
      };
    }
    return {
      display: 'flex',
      width: '100%',
      minWidth: '0',
      justifyContent: this.rightAlign ? 'flex-end' : 'flex-start',
    };
  }

  get tooltipStyle(): Record<string, string> {
    return this.useColumn
      ? { display: 'flex', alignItems: 'center' }
      : { marginLeft: '8px', display: 'flex', alignItems: 'center' };
  }
}

/**
 * InstanceName - editable instance name row above the field list
 */
@Component({
  selector: 'fv-instance-name',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div style="margin-bottom:16px">
      <div style="display:flex;align-items:center;gap:8px">
        <label style="font-size:0.85rem;color:var(--formitiva-color-text-muted, #888);white-space:nowrap">
          {{ ctx.t()('Instance name') }}:
        </label>
        <input
          type="text"
          [value]="name"
          (input)="onInput($event)"
          style="flex:1;font-size:0.85rem;border:1px solid var(--formitiva-border-color,#ccc);border-radius:var(--formitiva-border-radius,4px);padding:2px 6px;background:transparent;color:inherit;outline:none"
        />
      </div>
    </div>
  `,
})
export class InstanceNameComponent {
  @Input({ required: true }) name!: string;
  @Input({ required: true }) onChange!: (n: string) => void;

  readonly ctx = inject(FormitivaContextService);

  onInput(event: Event): void {
    this.onChange((event.target as HTMLInputElement).value);
  }
}
