// packages/vue/src/components/fields/advanced/SliderInput.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { StandardFieldLayout } from "../../layout/LayoutComponents";
import type { BaseInputProps, DefinitionPropertyField } from '@formitiva/core';
import { CSS_CLASSES, combineClasses } from '@formitiva/core';
import { useFieldValidator } from "../../../hooks/useFieldValidator";

type SliderInputProps = BaseInputProps<string | number, DefinitionPropertyField>;

const props = defineProps<SliderInputProps>();

const emit = defineEmits<{
  change: [value: string | number];
  error: [error: string | null];
}>();

const validate = useFieldValidator(props.field, props.error);

const min = props.field.min ?? 0;
const max = props.field.max ?? 100;

const inputValue = ref(!isNaN(Number(props.value)) ? String(Number(props.value)) : String(min));

watch(() => props.value, (newValue) => {
  const newVal = !isNaN(Number(newValue)) ? String(Number(newValue)) : String(min);
  inputValue.value = newVal;
});

const error = ref<string | null>(null);
const prevError = ref<string | null>(null);

const updateError = (next: string | null) => {
  if (next !== prevError.value) {
    prevError.value = next;
    error.value = next;
    emit('error', next);
  }
};

watch(inputValue, (newVal) => {
  updateError(validate(newVal, "sync") ?? null);
});

const handleValueChange = (e: Event) => {
  const target = e.target as HTMLInputElement;
  const input = target.value;
  inputValue.value = input;
  updateError(validate(input, "change") ?? null);
  emit('change', input);
};

const handleBlur = (e: Event) => {
  const target = e.target as HTMLInputElement;
  updateError(validate(target.value, "blur") ?? null);
};

const displayValue = computed(() => 
  !isNaN(Number(inputValue.value)) ? String(Number(inputValue.value)) : String(min)
);
</script>

<template>
  <StandardFieldLayout :field="field" :error="error">
    <div style="display: flex; align-items: center; gap: 8px; width: 100%;">
      <input
        :id="`${field.name}-range`"
        type="range"
        :value="displayValue"
        @input="handleValueChange"
        @blur="handleBlur"
        :min="min"
        :max="max"
        :step="props.field.step ?? 1"
        style="padding: 0; flex: 1;"
        :class="CSS_CLASSES.rangeInput"
        :aria-invalid="!!error"
        :aria-describedby="error ? `${field.name}-error` : undefined"
      />
      <div style="width: 40px; text-align: center;">{{ displayValue }}</div>
      <input
        :id="field.name"
        type="text"
        :value="inputValue"
        @input="handleValueChange"
        @blur="handleBlur"
        required
        style="
          width: 40px;
          min-width: 40px;
          height: 2.3em;
          text-align: center;
          flex-shrink: 0;
        "
        :class="combineClasses(CSS_CLASSES.input, CSS_CLASSES.textInput)"
        :aria-invalid="!!error"
        :aria-describedby="error ? `${field.name}-error` : undefined"
      />
    </div>
  </StandardFieldLayout>
</template>

// packages/react/src/components/fields/advanced/SliderInput.tsx
import * as React from "react";
import { StandardFieldLayout } from "../../layout/LayoutComponents";
import type { BaseInputProps, DefinitionPropertyField } from '@formitiva/core';
import { CSS_CLASSES, combineClasses } from '@formitiva/core';
import { useFieldValidator } from "../../../hooks/useFieldValidator";

type SliderInputProps = BaseInputProps<string | number, DefinitionPropertyField>;

const SliderInput: React.FC<SliderInputProps> = ({ field, value, onChange, onError, error: externalError }) => {
  const validate = useFieldValidator(field, externalError);
  
  const min = field.min ?? 0;
  const max = field.max ?? 100;

  // Controlled state
  const [inputValue, setInputValue] = React.useState(() =>
    !isNaN(Number(value)) ? String(Number(value)) : String(min)
  );

  // Sync with props
  React.useEffect(() => {
    const newVal = !isNaN(Number(value)) ? String(Number(value)) : String(min);
    setInputValue(newVal);
  }, [value, min]);

  const [error, setError] = React.useState<string | null>(null);
  const prevErrorRef = React.useRef<string | null>(null);
  const onErrorRef = React.useRef(onError);

  React.useEffect(() => {
    onErrorRef.current = onError;
  }, [onError]);

  const updateError = React.useCallback((next: string | null) => {
    if (next !== prevErrorRef.current) {
      prevErrorRef.current = next;
      setError(next);
      onErrorRef.current?.(next ?? null);
    }
  }, []);

  React.useEffect(() => {
    updateError(validate(inputValue, "sync") ?? null);
  }, [validate, inputValue, updateError]);

  // Handle changes from both range and text inputs
  const handleValueChange = React.useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const input = e.target.value;
      setInputValue(input);
      updateError(validate(input, "change") ?? null);
      onChange?.(input);
    },
    [onChange, updateError, validate]
  );

  const handleBlur = React.useCallback(
    (e: React.FocusEvent<HTMLInputElement>) => {
      updateError(validate(e.target.value, "blur") ?? null);
    },
    [updateError, validate]
  );

  const displayValue = !isNaN(Number(inputValue)) ? String(Number(inputValue)) : String(min);

  return (
    <StandardFieldLayout field={field} error={error}>
      <div style={{ display: "flex", alignItems: "center", gap: "8px", width: "100%" }}>
        <input
          id={`${field.name}-range`}
          type="range"
          value={displayValue}
          onChange={handleValueChange}
          onBlur={handleBlur}
          min={min}
          max={max}
          step="1.0"
          style={{
            padding: 0,
            flex: 1,
          }}
          className={CSS_CLASSES.rangeInput}
          aria-invalid={!!error}
          aria-describedby={error ? `${field.name}-error` : undefined}
        />
        <input
          id={field.name}
          type="text"
          value={inputValue}
          onChange={handleValueChange}
          onBlur={handleBlur}
          required
          style={{
            width: "40px",
            minWidth: "40px",
            height: "2.3em",
            textAlign: "center",
            flexShrink: 0,
          }}
          className={combineClasses(CSS_CLASSES.input, CSS_CLASSES.textInput)}
          aria-invalid={!!error}
          aria-describedby={error ? `${field.name}-error` : undefined}
        />
      </div>
    </StandardFieldLayout>
  );
};

SliderInput.displayName = "SliderInput";
export default React.memo(SliderInput);
