// packages/react/src/components/form/FormitivaRenderer.tsx
import * as React from "react";
import type {
  FieldValueType,
  ErrorType,
  DefinitionPropertyField,
  FormitivaDefinition,
  FormitivaInstance,
  FormSubmissionHandler,
  FormValidationHandler,
} from '@formitiva/core';
import { getLayout } from '@formitiva/core';
import useFormitivaContext, { FormitivaContext } from "../../hooks/useFormitivaContext";
import { FieldRenderer } from "../layout/FieldRenderer";
import { FieldGroup } from "../layout/FieldGroup";
import { InstanceName } from "../layout/LayoutComponents";
import { getLayoutAdapter } from '../../core/registries/layoutAdapterRegistry';
import {
  initFormState,
  computeFieldChange,
  computeVisibleGroups,
  computeSubmitErrors,
  isSubmitDisabled,
} from '@formitiva/core';
import type { FieldVisibilityStatus } from '@formitiva/core';
import { submitForm } from '@formitiva/core';
import { SubmissionMessage } from "./SubmissionMessage";

export interface FormitivaRendererProps {
  definition: FormitivaDefinition;
  instance: FormitivaInstance;
  onSubmit?: FormSubmissionHandler;
  onValidation?: FormValidationHandler;
  chunkSize?: number;
  chunkDelay?: number;
}

/**
 * FormitivaRenderer component - Internal form renderer with field management
 * @param {FormitivaRendererProps} props - The component props
 * @param {FormitivaDefinition} props.definition - The form definition object
 * @param {FormitivaInstance} props.instance - The form instance with values
 * @param {number} [props.chunkSize=50] - Number of fields to render per chunk for performance
 * @param {number} [props.chunkDelay=50] - Delay in ms between rendering chunks
 */
const FormitivaRenderer: React.FC<FormitivaRendererProps> = ({
  definition,
  instance,
  onSubmit = undefined,
  onValidation = undefined,
  chunkSize = 50,
  chunkDelay = 50,
}) => {
  const { properties, displayName } = definition;
  const parentContext = useFormitivaContext();
  const { t, formStyle, language, displayInstanceName } = parentContext;
  const renderContext = {
    ...parentContext,
    definitionName: definition?.name ?? parentContext.definitionName,
  };
  const [ savedLanguage, setSavedLanguage] = React.useState("en");

  // Layout adapter registry
  const activeLayout = getLayout(definition?.layoutRef ?? '');
  const LayoutAdapter = getLayoutAdapter();

  // Core state
  const [updatedProperties, setUpdatedProperties] = React.useState<
    DefinitionPropertyField[]
  >([]);
  const [fieldMap, setFieldMap] = React.useState<
    Record<string, DefinitionPropertyField>
  >({});
  const [valuesMap, setValuesMap] = React.useState<Record<string, FieldValueType>>(
    {}
  );
  const [visibility, setVisibility] = React.useState<Record<string, boolean>>({});
  const [visibilityRefStatus, setVisibilityRefStatus] = React.useState<Record<string, FieldVisibilityStatus>>({});
  const [disabledByRef, setDisabledByRef] = React.useState<Record<string, boolean>>({});
  const [errors, setErrors] = React.useState<Record<string, string>>({});
  const [submissionMessage, setSubmissionMessage] = React.useState<string | null>(null);
  const [submissionSuccess, setSubmissionSuccess] = React.useState<boolean | null>(null);

  const [loadedCount, setLoadedCount] = React.useState(0); // how many fields are loaded so far
  const [initDone, setInitDone] = React.useState(false);
  
  const [instanceName, setInstanceName] = React.useState<string>(instance.name || '');
  const targetInstanceRef = React.useRef<FormitivaInstance>(instance);
  const suppressClearOnNextInstanceUpdate = React.useRef(false);
  const valuesMapRef = React.useRef(valuesMap);
  React.useEffect(() => { valuesMapRef.current = valuesMap; }, [valuesMap]);

 
  // Step 1: Initialize basic structures immediately
  React.useEffect(() => {
    const init = initFormState(definition, instance, t);
    const raf = requestAnimationFrame(() => {
      setUpdatedProperties(init.updatedProperties);
      setFieldMap(init.nameToField);
      setValuesMap(init.valuesMap);
      setVisibility(init.visibility);
      setVisibilityRefStatus(init.visibilityRefStatus);
      setDisabledByRef(init.disabledByRef);
      setInitDone(true);
      setInstanceName(instance.name);
    });
    return () => cancelAnimationFrame(raf);
  }, [properties, instance, definition]);

  // Step 2: Load fields progressively
  React.useEffect(() => {
    if (!initDone || loadedCount >= updatedProperties.length) return;
    const timer = setTimeout(() => {
      setLoadedCount((prev) =>
        Math.min(prev + chunkSize, updatedProperties.length)
      );
    }, chunkDelay);
    return () => clearTimeout(timer);
  }, [initDone, loadedCount, updatedProperties.length, chunkSize, chunkDelay]);

  /*
   * handleChange
   * ----------------
   * This is the central field change handler passed down to rendered field
   * components. Contract:
   * - name: the field name being changed
   * - value: the new value for the field (may be any FieldValueType)
   * - error: optional validation error string
   *
   * Responsibilities:
   * 1. Update the local values map (using a functional update so we always
   *    operate on the latest state and avoid stale closures).
   * 2. Update the visibility map when the changed field affects conditional
   *    visibility (options/select/radio/multi-select/boolean). Visibility is
   *    recomputed from the new values so dependent fields show/hide correctly.
   */
  const handleChange = React.useCallback(
    (name: string, value: FieldValueType) => {
      const field = fieldMap[name];
      if (!field) return;

      setSubmissionMessage(null);
      setSubmissionSuccess(null);

      setValuesMap((prevValues) => {
        const changed = computeFieldChange(name, value, {
          fieldMap,
          updatedProperties,
          valuesMap: prevValues,
          visibility,
        }, t);
        if (changed.newVisibility !== visibility) {
          setVisibility(changed.newVisibility);
        }
        setVisibilityRefStatus(changed.newVisRefStatus);
        setDisabledByRef(changed.newDisabledByRef);
        return changed.newValues;
      });
    },
    [fieldMap, updatedProperties, visibility, t]
  );

  // Sync language changes: update savedLanguage and clear messages
  // Use RAF to avoid cascading renders.
  React.useEffect(() => {
    let raf = 0;
    raf = requestAnimationFrame(() => {
      if (language !== savedLanguage) {
        setSavedLanguage(language || "en");
        setSubmissionMessage(null);
        setSubmissionSuccess(null);
      }
    });
    return () => cancelAnimationFrame(raf);
  }, [language, savedLanguage]);

  // When the active instance changes (selection switched), clear submission messages
  // and sync the editable instance name and ref. Use RAF to avoid cascading renders.
  React.useEffect(() => {
    let raf = 0;
    raf = requestAnimationFrame(() => {
      // If this instance update was caused by our own successful submit,
      // skip clearing the submission message but still sync the editable name.
      if (suppressClearOnNextInstanceUpdate.current) {
        suppressClearOnNextInstanceUpdate.current = false;
        // Keep ref in sync with latest instance object
        targetInstanceRef.current = instance;
        setInstanceName(instance.name || "");
        return;
      }

      // Keep ref in sync with latest instance object
      targetInstanceRef.current = instance;
      setSubmissionMessage(null);
      setSubmissionSuccess(null);
      setInstanceName(instance.name || "");
    });
    return () => cancelAnimationFrame(raf);
  }, [instance, instance.name]);

  // handleError: used by input components to report validation-only updates
  // that originate from prop sync (not user events). This keeps the error
  // map up to date when components validate on mount or when external props
  // change without invoking the full handleChange lifecycle.
  const handleError = React.useCallback((name: string, error: ErrorType) => {
    if (fieldMap[name]?.disabled) {
      setErrors((prev) => {
        if (!(name in prev)) return prev;
        const rest = Object.fromEntries(Object.entries(prev).filter(([k]) => k !== name)) as Record<string, string>;
        return rest;
      });
      return;
    }

    setErrors((prev) => {
      if (error) {
        return { ...prev, [name]: String(error) };
      }
      // remove key
      const rest = Object.fromEntries(Object.entries(prev).filter(([k]) => k !== name)) as Record<string, string>;
      return rest;
    });
  }, [fieldMap]);

  const handleSubmit = async () => {
    suppressClearOnNextInstanceUpdate.current = true;
    const prevName = targetInstanceRef.current?.name;
    targetInstanceRef.current.name = instanceName;

    let errorsForSubmit = errors;

    if (renderContext.fieldValidationMode === "onSubmission") {
      const newErrors = computeSubmitErrors(updatedProperties, valuesMap, renderContext.definitionName, t);
      setErrors(newErrors);
      errorsForSubmit = newErrors;

      if (Object.keys(newErrors).length > 0) {
        setSubmissionMessage(t("Please fix validation errors before submitting the form."));
        setSubmissionSuccess(false);
        return;
      } else {
        setSubmissionMessage(null);
        setSubmissionSuccess(null);
      }
    }

    const result = await submitForm(definition, targetInstanceRef.current, valuesMap, t, errorsForSubmit, onSubmit, onValidation);
    const msg = typeof result.message === 'string' ? result.message : String(result.message);
    const errMsg = Object.values(result.errors ?? {}).join("\n");
    setSubmissionMessage(errMsg ? msg + "\n" + errMsg : msg);
    setSubmissionSuccess(result.success);

    if (!result.success) {
      targetInstanceRef.current.name = prevName ?? targetInstanceRef.current.name;
      setInstanceName(prevName ?? "");
    }
  };

  const isApplyDisabled = React.useMemo(
    () => isSubmitDisabled(renderContext.fieldValidationMode, errors),
    [errors, renderContext.fieldValidationMode]
  );

  // Render fields �� optionally filtered to the given field names
  const renderFields = (fieldNames?: string[]) => {
    const filtered = fieldNames
      ? updatedProperties.filter((p) => fieldNames.includes(p.name))
      : updatedProperties;
    const groups = computeVisibleGroups(filtered, visibility, visibilityRefStatus, loadedCount);

    return (
      <>
        {groups.map((group, index) => {
          if (group.name) {
            return (
              <FieldGroup
                key={group.name}
                groupName={group.name}
                defaultOpen={true}
                fields={group.fields}
                valuesMap={valuesMap}
                handleChange={handleChange}
                handleError={handleError}
                errorsMap={errors}
                t={t}
                disabledByRef={disabledByRef}
              />
            );
          }
          return (
            <React.Fragment key={`ungrouped-${index}`}>
              {group.fields.map((field) => (
                <FieldRenderer
                  key={field.name}
                  field={field}
                  valuesMap={valuesMap}
                  handleChange={handleChange}
                  handleError={handleError}
                  errorsMap={errors}
                  disabledByRef={disabledByRef}
                />
              ))}
            </React.Fragment>
          );
        })}
        {loadedCount < updatedProperties.length && (
          <div style={{ fontSize: '0.9em', color: 'var(--formitiva-text-muted, #666)' }}>
            {t(`Loading more fields...` + ` (${loadedCount}/${updatedProperties.length})`)}
          </div>
        )}
      </>
    );
  };

  const renderSubmit = () => (
    <button onClick={handleSubmit} disabled={isApplyDisabled} className="formitiva-button" style={{ width: "120px" }}>
      {t("Submit")}
    </button>
  );

  return (
    <FormitivaContext.Provider value={renderContext}>
      <div style={formStyle.container}>
      {displayName && <h2 style={formStyle.titleStyle}>{t(displayName)}</h2>}
      {/* Display submission message on top*/}
      <SubmissionMessage
        message={submissionMessage}
        success={submissionSuccess}
        onDismiss={() => { setSubmissionMessage(null); setSubmissionSuccess(null); }}
        t={t}
      />
      {displayInstanceName && instance && (
        <InstanceName
          name={instanceName}
          onChange={(newName) => {
            // Only update the editable local name here. The actual instance
            // object's name will be updated only if a submit succeeds.
            setInstanceName(newName);
            setSubmissionMessage(null);
            setSubmissionSuccess(null);
          }}
        />
      )}
      {LayoutAdapter && activeLayout
        ? <LayoutAdapter layout={activeLayout} renderFields={renderFields} renderSubmit={renderSubmit} t={t} />
        : <>{renderFields()}{renderSubmit()}</>}
      </div>
    </FormitivaContext.Provider>
  );
};

export default FormitivaRenderer;

// packages/vue/src/components/form/FormitivaRenderer.vue
<script setup lang="ts">
import { ref, computed, watch, watchEffect, reactive, onUnmounted } from 'vue';
import type { DefinitionPropertyField, FormitivaContextType } from '@formitiva/core';
import type {
  FieldValueType,
  ErrorType,
  FormitivaDefinition,
  FormitivaInstance,
  FormSubmissionHandler,
  FormValidationHandler,
} from '@formitiva/core';
import { getLayout } from '@formitiva/core';
import useFormitivaContext, { provideFormitivaContext } from '../../hooks/useFormitivaContext';
import FieldRenderer from '../layout/FieldRenderer.vue';
import FieldGroup from '../layout/FieldGroup.vue';
import { InstanceName } from '../layout/LayoutComponents';
import { getLayoutAdapter } from '../../core/registries/layoutAdapterRegistry';
import {
  initFormState,
  computeFieldChange,
  computeVisibleGroups,
  computeSubmitErrors,
  isSubmitDisabled,
} from '@formitiva/core';
import type { FieldVisibilityStatus } from '@formitiva/core';
import { submitForm } from '@formitiva/core';
import SubmissionMessage from './SubmissionMessage.vue';
import SubmissionButton from './SubmissionButton.vue';

export interface FormitivaRendererProps {
  definition: FormitivaDefinition;
  instance: FormitivaInstance;
  onSubmit?: FormSubmissionHandler;
  onValidation?: FormValidationHandler;
}

const props = withDefaults(defineProps<FormitivaRendererProps>(), {
  onSubmit: undefined,
  onValidation: undefined,
});

const { displayName } = props.definition;
const parentContext = useFormitivaContext();

// Layout adapter
const activeLayout = getLayout(props.definition?.layoutRef ?? '');
const layoutAdapter = getLayoutAdapter();
const activeSection = ref<string>(activeLayout?.defaultValue ?? '');

// Reset section when layout changes
watch(() => activeLayout?.defaultValue, (val) => {
  activeSection.value = val ?? '';
}, { immediate: true });

const renderContext = computed(() => ({
  ...parentContext,
  definitionName: props.definition?.name ?? parentContext.definitionName,
}));

// Read t, formStyle, displayInstanceName from renderContext so they stay
// reactive when translation maps reload or theme/style changes
const t = computed(() => renderContext.value.t);
const formStyle = computed(() => renderContext.value.formStyle);
const displayInstanceName = computed(() => renderContext.value.displayInstanceName);

const updatedProperties = ref<DefinitionPropertyField[]>([]);
const fieldMap = ref<Record<string, DefinitionPropertyField>>({});
const computedRefFields = ref<DefinitionPropertyField[]>([]);
const visibilityRefFields = ref<DefinitionPropertyField[]>([]);
const valuesMap = ref<Record<string, FieldValueType>>({});
const visibility = ref<Record<string, boolean>>({});
const visibilityRefStatus = ref<Record<string, FieldVisibilityStatus>>({});
const disabledByRef = ref<Record<string, boolean>>({});
const errors = ref<Record<string, string>>({});
const submissionMessage = ref<string | null>(null);
const submissionSuccess = ref<boolean | null>(null);
const instanceName = ref<string>(props.instance.name || '');
const targetInstance = ref<FormitivaInstance>(props.instance);
const suppressClearOnNextInstanceUpdate = ref(false);

// Progressive rendering state
const loadedCount = ref(0);
const initDone = ref(false);
const chunkSize = 50;
const chunkDelay = 50;
let chunkTimer: ReturnType<typeof setTimeout> | undefined;

const scheduleChunk = () => {
  if (!initDone.value || loadedCount.value >= updatedProperties.value.length) return;
  chunkTimer = setTimeout(() => {
    loadedCount.value = Math.min(loadedCount.value + chunkSize, updatedProperties.value.length);
    scheduleChunk();
  }, chunkDelay);
};

onUnmounted(() => {
  if (chunkTimer) clearTimeout(chunkTimer);
});

// Initialize all state so fields are visible on first render
const initialize = () => {
  if (chunkTimer) { clearTimeout(chunkTimer); chunkTimer = undefined; }
  const init = initFormState(props.definition, props.instance, t.value);
  targetInstance.value = props.instance;
  updatedProperties.value = init.updatedProperties;
  fieldMap.value = init.nameToField;
  computedRefFields.value = init.computedRefFields;
  visibilityRefFields.value = init.visibilityRefFields;
  valuesMap.value = init.valuesMap;
  visibility.value = init.visibility;
  visibilityRefStatus.value = init.visibilityRefStatus;
  disabledByRef.value = init.disabledByRef;
  instanceName.value = props.instance.name;
  loadedCount.value = 0;
  initDone.value = true;
  scheduleChunk();
};

watch([() => props.definition, () => props.instance], initialize, { immediate: true });

// Handle field change
const handleChange = (name: string, value: FieldValueType) => {
  const field = fieldMap.value[name];
  if (!field) return;

  submissionMessage.value = null;
  submissionSuccess.value = null;

  const changed = computeFieldChange(name, value, {
    fieldMap: fieldMap.value,
    updatedProperties: updatedProperties.value,
    valuesMap: valuesMap.value,
    visibility: visibility.value,
    computedRefFields: computedRefFields.value,
    visibilityRefFields: visibilityRefFields.value,
  }, t.value);

  valuesMap.value = changed.newValues;
  visibility.value = changed.newVisibility;
  visibilityRefStatus.value = changed.newVisRefStatus;
  disabledByRef.value = changed.newDisabledByRef;
};

// When active instance changes
watch(() => props.instance, (newInstance) => {
  if (suppressClearOnNextInstanceUpdate.value) {
    suppressClearOnNextInstanceUpdate.value = false;
    targetInstance.value = newInstance;
    instanceName.value = newInstance.name || "";
    return;
  }

  targetInstance.value = newInstance;
  submissionMessage.value = null;
  submissionSuccess.value = null;
  instanceName.value = newInstance.name || "";
});

// Handle error
const handleError = (name: string, error: ErrorType) => {
  if (fieldMap.value[name]?.disabled) {
    const rest = { ...errors.value } as Record<string, string>;
    delete rest[name];
    errors.value = rest;
    return;
  }

  if (error) {
    errors.value = { ...errors.value, [name]: String(error) };
    } else {
    const rest = { ...errors.value } as Record<string, string>;
    delete rest[name];
    errors.value = rest;
  }
};

// Handle submit
const handleSubmit = async () => {
  suppressClearOnNextInstanceUpdate.value = true;

  const prevName = targetInstance.value?.name;
  targetInstance.value.name = instanceName.value;

  let errorsForSubmit = errors.value;

  if (renderContext.value.fieldValidationMode === "onSubmission") {
    const newErrors = computeSubmitErrors(
      updatedProperties.value,
      valuesMap.value,
      renderContext.value.definitionName,
      t.value,
    );
    errors.value = newErrors;
    errorsForSubmit = newErrors;

    if (Object.keys(newErrors).length > 0) {
      submissionMessage.value = t.value("Please fix validation errors before submitting the form.");
      submissionSuccess.value = false;
      return;
    } else {
      submissionMessage.value = null;
      submissionSuccess.value = null;
    }
  }

  try {
    const result = await submitForm(
      props.definition,
      targetInstance.value,
      valuesMap.value,
      t.value,
      errorsForSubmit,
      props.onSubmit,
      props.onValidation
    );

    const msg = typeof result.message === 'string' ? result.message : String(result.message);
    const errMsg = Object.values(result.errors ?? {}).join("\n");
    submissionMessage.value = errMsg ? msg + "\n" + errMsg : msg;
    submissionSuccess.value = result.success;

    if (!result.success) {
      targetInstance.value.name = prevName ?? targetInstance.value.name;
      instanceName.value = prevName ?? "";
    }
  } catch (err) {
    console.error('[Formitiva] Form submission threw an unexpected error:', err);
    submissionMessage.value = t.value('An unexpected error occurred. Please try again.');
    submissionSuccess.value = false;
    targetInstance.value.name = prevName ?? targetInstance.value.name;
    instanceName.value = prevName ?? "";
  }
};

const hasErrorsInFields = (fieldNames?: string[] | null) => {
  if (!fieldNames?.length) {
    return false;
  }

  const fields = updatedProperties.value.filter((field) => fieldNames.includes(field.name));
  return Object.keys(
    computeSubmitErrors(
      fields,
      valuesMap.value,
      renderContext.value.definitionName,
      t.value,
    ),
  ).length > 0;
};

const isApplyDisabled = computed(() =>
  isSubmitDisabled(renderContext.value.fieldValidationMode, errors.value)
);

// Compute which field names belong to the active layout section
const activeSectionProps = computed<string[] | null>(() => {
  if (!activeLayout) return null;
  return activeLayout.sections.find((n) => n.name === activeSection.value)?.props ?? null;
});

const isNextDisabled = computed(() => hasErrorsInFields(activeSectionProps.value));

// Filter updatedProperties to only the current section's fields
const sectionProperties = computed<DefinitionPropertyField[]>(() => {
  const propsFilter = activeSectionProps.value;
  if (!propsFilter) return updatedProperties.value;
  return updatedProperties.value.filter((p) => propsFilter.includes(p.name));
});

const groups = computed(() =>
  computeVisibleGroups(
    sectionProperties.value,
    visibility.value,
    visibilityRefStatus.value,
    layoutAdapter && activeLayout ? undefined : loadedCount.value,
  )
);

// Provide a reactive render context once and keep it in sync with renderContext.
const providedRenderContext = reactive({ ...(renderContext.value as Record<string, unknown>) }) as unknown as FormitivaContextType;
provideFormitivaContext(providedRenderContext);
watchEffect(() => {
  Object.assign(providedRenderContext, renderContext.value as unknown as Record<string, unknown>);
});
</script>

<template>
  <div :style="formStyle.container">
    <h2 v-if="displayName" :style="formStyle.titleStyle">{{ t(displayName) }}</h2>
    
    <SubmissionMessage
      :message="submissionMessage"
      :success="submissionSuccess"
      :t="t"
      @dismiss="() => { submissionMessage = null; submissionSuccess = null; }"
    />
    
    <InstanceName
      v-if="displayInstanceName && instance"
      :name="instanceName"
      @change="(newName: string) => {
        instanceName = newName;
        submissionMessage = null;
        submissionSuccess = null;
      }"
    />

    <!-- Layout adapter (pro plugin) -->
    <component
      v-if="layoutAdapter && activeLayout"
      :is="layoutAdapter"
      :layout="activeLayout"
      :next-disabled="isNextDisabled"
      :model-value="activeSection"
      @update:model-value="(name: string) => { activeSection = name; }"
    >
      <template v-for="(group, index) in groups" :key="group.name || `ungrouped-${index}`">
        <FieldGroup
          v-if="group.name"
          :group-name="group.name"
          :default-open="true"
          :fields="group.fields"
          :values-map="valuesMap"
          :errors-map="errors"
          :t="t"
          :handleChange="handleChange"
          :handleError="handleError"
          :disabled-by-ref="disabledByRef"
        />
        <template v-else>
          <FieldRenderer
            v-for="field in group.fields"
            :key="field.name"
            :field="field"
            :values-map="valuesMap"
            :errors-map="errors"
            :handleChange="handleChange"
            :handleError="handleError"
            :disabled-by-ref="disabledByRef"
          />
        </template>
      </template>
      <template #submit>
        <SubmissionButton :disabled="isApplyDisabled" :t="t" @click="handleSubmit" />
      </template>
    </component>

    <!-- Normal layout (no adapter) -->
    <template v-else>
      <template v-for="(group, index) in groups" :key="group.name || `ungrouped-${index}`">
        <FieldGroup
          v-if="group.name"
          :group-name="group.name"
          :default-open="true"
          :fields="group.fields"
          :values-map="valuesMap"
          :errors-map="errors"
          :t="t"
          :handleChange="handleChange"
          :handleError="handleError"
          :disabled-by-ref="disabledByRef"
        />
        <template v-else>
          <FieldRenderer
            v-for="field in group.fields"
            :key="field.name"
            :field="field"
            :values-map="valuesMap"
            :errors-map="errors"
            :handleChange="handleChange"
            :handleError="handleError"
            :disabled-by-ref="disabledByRef"
          />
        </template>
      </template>
    </template>

    <!-- Submit button: only rendered when no layout adapter is active -->
    <div
      v-if="(!layoutAdapter || !activeLayout) && loadedCount < updatedProperties.length"
      style="font-size:0.9em;color:var(--formitiva-text-muted, #666)"
    >
      {{ t(`Loading more fields... (${loadedCount}/${updatedProperties.length})`) }}
    </div>
    <SubmissionButton
      v-if="!layoutAdapter || !activeLayout"
      :disabled="isApplyDisabled" 
      :t="t"
      @click="handleSubmit" 
    />
  </div>
</template>
