// packages/react/src/components/form/Formitiva.tsx

import * as React from "react";
import FormitivaRenderer from "./FormitivaRenderer";
import { FormitivaProvider } from "./FormitivaProvider";
import { createInstanceFromDefinition } from '@formitiva/core';
import type { FormitivaDefinition, FormitivaProps } from '@formitiva/core';

function useNearestFormitivaTheme(ref?: React.RefObject<HTMLElement>) {
  const [theme, setTheme] = React.useState<string | null>(null);
  React.useEffect(() => {
    const startEl = ref?.current ?? document.querySelector('[data-formitiva-theme]');
    if (!startEl) return;
    const themedNode = (startEl as Element).closest('[data-formitiva-theme]') as Element | null;
    if (!themedNode) return;
    const read = () => setTheme(themedNode.getAttribute('data-formitiva-theme'));
    read();

    const mo = new MutationObserver((mutations) => {
      for (const m of mutations) {
        if (m.type === 'attributes' && (m as MutationRecord).attributeName === 'data-formitiva-theme') {
          read();
        }
      }
    });
    mo.observe(themedNode, { attributes: true, attributeFilter: ['data-formitiva-theme'] });
    return () => mo.disconnect();
  }, [ref]);
  return theme;
}

/**
 * Formitiva component - The main form rendering component
 * @param {FormitivaProps} props - The component props
 * @param {string | Record<string, unknown> | FormitivaDefinition} props.definitionData - Form definition data (JSON string, object, or FormitivaDefinition)
 * @param {FormitivaInstance} [props.instance] - Optional form instance with saved values
 * @param {string} [props.language] - Language code for localization
 * @param {string} [props.className] - Additional CSS class names
 * @param {string} [props.theme] - Theme name ('light' or 'dark')
 * @param {React.CSSProperties} [props.style] - Inline styles
 * @param {FieldValidationMode} [props.fieldValidationMode] - Field Validation mode ('onEdit', 'onBlur', 'onSubmission', 'realTime' [deprecated])
 * @param {boolean} [props.displayInstanceName] - Whether to display the instance name
 */
const Formitiva: React.FC<FormitivaProps> = ({
  definitionData,
  instance,
  language,
  className,
  theme,
  style, 
  fieldValidationMode: validationMode = 'onEdit',
  displayInstanceName = true,
  onSubmit = undefined,
  onValidation = undefined,
}) => {
    const definition = React.useMemo<FormitivaDefinition | null>(() => {
      try {
        return typeof definitionData === 'string' ? JSON.parse(definitionData) : (definitionData ?? null);
      } catch {
        return null;
      }
    }, [definitionData]);
    const inputStyle = { fontSize: "inherit", fontFamily: "inherit", ...style };
    
    const detectedTheme = useNearestFormitivaTheme();
    const inputTheme = theme ?? detectedTheme ?? 'light';

    const inputLanguage = language ?? 'en';

    React.useEffect(() => {
      // Add popup-root div if not already present to make sure popups work
      let root = document.getElementById('popup-root');
      if (!root) {
        root = document.createElement('div');
        root.id = 'popup-root';
        document.body.appendChild(root);
      }
    }, []);

    // Ensure we always have an instance to pass to the renderer. If the
    // caller didn't provide one, create a new instance from the definition.
    // We memoize this to prevent creating a new instance on every render,
    // which would reset the form state.
    const resolvedInstance = React.useMemo(() => {
      if (instance) return instance;
      if (!definition) return null;

      const created = createInstanceFromDefinition(definition, definition.name);
      if (!created.success || !created.instance) {
        return null;
      }
      return created.instance;
    }, [instance, definition]);

    if (!definition) {
      return <div style={{ color: 'red' }}>Error: No form definition provided.</div>;
    }

    if (!resolvedInstance) {
      return <div style={{ color: 'red' }}>Error: Failed to create instance from definition.</div>;
    }

    return (
      <FormitivaProvider
        definitionName={definition.name}
        defaultStyle={inputStyle}
        defaultLanguage={inputLanguage}
        defaultTheme={inputTheme}
        defaultLocalizeName={definition.localization || ""}
        className={className}
        defaultFieldValidationMode={validationMode}
        defaultDisplayInstanceName={displayInstanceName}
      >
        <FormitivaRenderer
          definition={definition}
          instance={resolvedInstance}
          onSubmit={onSubmit}
          onValidation={onValidation}
        />
      </FormitivaProvider>
    );
};

export default Formitiva;

// packages/vue/src/components/form/Formitiva.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue';
import FormitivaRenderer from './FormitivaRenderer.vue';
import FormitivaProvider from './FormitivaProvider.vue';
import { createInstanceFromDefinition } from '@formitiva/core';
import type { FormitivaDefinition, FormitivaProps } from '@formitiva/core';

const props = withDefaults(defineProps<FormitivaProps>(), {
  language: 'en',
  theme: undefined,
  className: '',
  style: () => ({}),
  fieldValidationMode: 'onEdit',
  displayInstanceName: true,
  onSubmit: undefined,
  onValidation: undefined,
});

const detectedTheme = ref<string | null>(null);
let mutationObserver: MutationObserver | null = null;

const definition = computed<FormitivaDefinition | null>(() => {
  try {
    return typeof props.definitionData === 'string' 
      ? JSON.parse(props.definitionData) 
      : (props.definitionData ?? null);
  } catch {
    return null;
  }
});

const inputStyle = computed(() => ({
  fontSize: "inherit",
  fontFamily: "inherit",
  ...props.style
}));

const inputTheme = computed(() => props.theme ?? detectedTheme.value ?? 'light');
const inputLanguage = computed(() => props.language ?? 'en');

const resolvedInstance = computed(() => {
  if (props.instance) return props.instance;
  if (!definition.value) return null;

  const created = createInstanceFromDefinition(definition.value, definition.value.name);
  if (!created.success || !created.instance) {
    return null;
  }
  return created.instance;
});

// Theme detection
onMounted(() => {
  const startEl = document.querySelector('[data-formitiva-theme]');
  if (startEl) {
    const themedNode = startEl.closest('[data-formitiva-theme]') as Element | null;
    if (themedNode) {
      const read = () => {
        detectedTheme.value = themedNode.getAttribute('data-formitiva-theme');
      };
      read();

      mutationObserver = new MutationObserver((mutations) => {
        for (const m of mutations) {
          if (m.type === 'attributes' && m.attributeName === 'data-formitiva-theme') {
            read();
          }
        }
      });
      mutationObserver.observe(themedNode, { 
        attributes: true, 
        attributeFilter: ['data-formitiva-theme'] 
      });
    }
  }

  // Add popup-root div if not already present
  let root = document.getElementById('popup-root');
  if (!root) {
    root = document.createElement('div');
    root.id = 'popup-root';
    document.body.appendChild(root);
  }
});

onUnmounted(() => {
  if (mutationObserver) {
    mutationObserver.disconnect();
  }
});
</script>

<template>
  <div v-if="!definition" style="color: red">
    Error: No form definition provided.
  </div>
  <div v-else-if="!resolvedInstance" style="color: red">
    Error: Failed to create instance from definition.
  </div>
  <FormitivaProvider
    v-else
    :definition-name="definition.name"
    :default-style="inputStyle"
    :default-language="inputLanguage"
    :default-theme="inputTheme"
    :default-localize-name="definition.localization || ''"
    :class-name="props.className || undefined"
    :default-field-validation-mode="props.fieldValidationMode"
    :default-display-instance-name="props.displayInstanceName"
    :on-submit="props.onSubmit"
    :on-validation="props.onValidation"
  >
    <FormitivaRenderer
      :definition="definition"
      :instance="resolvedInstance"
      :on-submit="onSubmit"
      :on-validation="onValidation"
    />
  </FormitivaProvider>
</template>
