// packages/angular/src/components/form/formitiva.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  Input,
  inject,
} from '@angular/core';
import type { OnChanges, OnDestroy, OnInit, SimpleChanges } from '@angular/core';
import { NgIf, NgStyle } from '@angular/common';
import { FormitivaContextService } from '../../services/formitiva-context.service';
import { FormitivaRendererComponent } from './formitiva-renderer.component';
import { createInstanceFromDefinition } from '@formitiva/core';
import { registerBaseComponents } from '../../core/registries/component-registry';
import { ensureBuiltinFieldTypeValidatorsRegistered } from '@formitiva/core';
import type {
  FormitivaDefinition,
  FormitivaInstance,
  FieldValidationMode,
  FormSubmissionHandler,
  FormValidationHandler,
} from '@formitiva/core';

registerBaseComponents();
ensureBuiltinFieldTypeValidatorsRegistered();

@Component({
  selector: 'fv-formitiva',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgIf, NgStyle, FormitivaRendererComponent],
  providers: [FormitivaContextService],
  template: `
    <div
      [attr.data-formitiva-theme]="resolvedTheme"
      [class]="className"
      [ngStyle]="wrapperStyle"
    >
      <div *ngIf="!definition" style="color:red">Error: No form definition provided.</div>
      <div *ngIf="definition && !resolvedInstance" style="color:red">Error: Failed to create instance from definition.</div>
      <fv-formitiva-renderer
        *ngIf="definition && resolvedInstance"
        [definition]="definition"
        [instance]="resolvedInstance"
        [onSubmit]="onSubmit"
        [onValidation]="onValidation"
      ></fv-formitiva-renderer>
    </div>
  `,
})
export class FormitivaComponent implements OnInit, OnChanges, OnDestroy {
  @Input() definitionData?: string | Record<string, unknown> | FormitivaDefinition;
  @Input() instance?: FormitivaInstance;
  @Input() language?: string;
  @Input() className = 'formitiva-container';
  @Input() theme?: string;
  @Input() style?: Record<string, string>;
  @Input() fieldValidationMode: FieldValidationMode = 'onEdit';
  @Input() displayInstanceName = true;
  @Input() onSubmit?: FormSubmissionHandler;
  @Input() onValidation?: FormValidationHandler;

  readonly ctx = inject(FormitivaContextService);

  definition: FormitivaDefinition | null = null;
  resolvedInstance: FormitivaInstance | null = null;
  resolvedTheme = 'light';
  wrapperStyle: Record<string, string> | null = null;

  private mo?: MutationObserver;
  private detectedTheme: string | null = null;

  ngOnInit(): void {
    this.parseDefinition();
    this.resolveInstance();
    this.configureContext();
    this.setupThemeObserver();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['definitionData']) this.parseDefinition();
    if (changes['instance'] || changes['definitionData']) this.resolveInstance();
    this.configureContext();
    if (changes['theme']) {
      this.resolvedTheme = this.theme ?? this.detectedTheme ?? 'light';
    }
  }

  ngOnDestroy(): void {
    this.mo?.disconnect();
  }

  private parseDefinition(): void {
    try {
      if (!this.definitionData) { this.definition = null; return; }
      this.definition = typeof this.definitionData === 'string'
        ? JSON.parse(this.definitionData) as FormitivaDefinition
        : this.definitionData as FormitivaDefinition;
    } catch {
      this.definition = null;
    }
  }

  private resolveInstance(): void {
    if (this.instance) { this.resolvedInstance = this.instance; return; }
    if (!this.definition) { this.resolvedInstance = null; return; }
    const result = createInstanceFromDefinition(this.definition, this.definition.name);
    this.resolvedInstance = (result.success && result.instance) ? result.instance : null;
  }

  private configureContext(): void {
    this.resolvedTheme = this.theme ?? this.detectedTheme ?? 'light';
    this.wrapperStyle = this.style ? { height: '100%' } : null;

    this.ctx.configure({
      definitionName: this.definition?.name ?? '',
      language: this.language ?? 'en',
      theme: this.resolvedTheme,
      fieldValidationMode: this.fieldValidationMode,
      displayInstanceName: this.displayInstanceName,
      defaultStyle: (this.style as Record<string, unknown>) ?? {},
      localizeName: this.definition?.localization ?? '',
    });
  }

  private setupThemeObserver(): void {
    if (typeof document === 'undefined') return;
    const el = document.querySelector('[data-formitiva-theme]') as Element | null;
    if (!el) return;
    this.detectedTheme = el.getAttribute('data-formitiva-theme');
    this.resolvedTheme = this.theme ?? this.detectedTheme ?? 'light';
    this.mo = new MutationObserver(mutations => {
      for (const m of mutations) {
        if (m.type === 'attributes' && m.attributeName === 'data-formitiva-theme') {
          this.detectedTheme = (m.target as Element).getAttribute('data-formitiva-theme');
          if (!this.theme) {
            this.resolvedTheme = this.detectedTheme ?? 'light';
            this.ctx.configure({ theme: this.resolvedTheme });
          }
        }
      }
    });
    this.mo.observe(el, { attributes: true, attributeFilter: ['data-formitiva-theme'] });
  }
}

// packages/vue/src/components/form/Formitiva.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue';
import FormitivaRenderer from './FormitivaRenderer.vue';
import FormitivaProvider from './FormitivaProvider.vue';
import { createInstanceFromDefinition } from '@formitiva/core';
import type { FormitivaDefinition, FormitivaProps } from '@formitiva/core';

const props = withDefaults(defineProps<FormitivaProps>(), {
  language: 'en',
  theme: undefined,
  className: '',
  style: () => ({}),
  fieldValidationMode: 'onEdit',
  displayInstanceName: true,
  onSubmit: undefined,
  onValidation: undefined,
});

const detectedTheme = ref<string | null>(null);
let mutationObserver: MutationObserver | null = null;

const definition = computed<FormitivaDefinition | null>(() => {
  try {
    return typeof props.definitionData === 'string' 
      ? JSON.parse(props.definitionData) 
      : (props.definitionData ?? null);
  } catch {
    return null;
  }
});

const inputStyle = computed(() => ({
  fontSize: "inherit",
  fontFamily: "inherit",
  ...props.style
}));

const inputTheme = computed(() => props.theme ?? detectedTheme.value ?? 'light');
const inputLanguage = computed(() => props.language ?? 'en');

const resolvedInstance = computed(() => {
  if (props.instance) return props.instance;
  if (!definition.value) return null;

  const created = createInstanceFromDefinition(definition.value, definition.value.name);
  if (!created.success || !created.instance) {
    return null;
  }
  return created.instance;
});

// Theme detection
onMounted(() => {
  const startEl = document.querySelector('[data-formitiva-theme]');
  if (startEl) {
    const themedNode = startEl.closest('[data-formitiva-theme]') as Element | null;
    if (themedNode) {
      const read = () => {
        detectedTheme.value = themedNode.getAttribute('data-formitiva-theme');
      };
      read();

      mutationObserver = new MutationObserver((mutations) => {
        for (const m of mutations) {
          if (m.type === 'attributes' && m.attributeName === 'data-formitiva-theme') {
            read();
          }
        }
      });
      mutationObserver.observe(themedNode, { 
        attributes: true, 
        attributeFilter: ['data-formitiva-theme'] 
      });
    }
  }

  // Add popup-root div if not already present
  let root = document.getElementById('popup-root');
  if (!root) {
    root = document.createElement('div');
    root.id = 'popup-root';
    document.body.appendChild(root);
  }
});

onUnmounted(() => {
  if (mutationObserver) {
    mutationObserver.disconnect();
  }
});
</script>

<template>
  <div v-if="!definition" style="color: red">
    Error: No form definition provided.
  </div>
  <div v-else-if="!resolvedInstance" style="color: red">
    Error: Failed to create instance from definition.
  </div>
  <FormitivaProvider
    v-else
    :definition-name="definition.name"
    :default-style="inputStyle"
    :default-language="inputLanguage"
    :default-theme="inputTheme"
    :default-localize-name="definition.localization || ''"
    :class-name="props.className || undefined"
    :default-field-validation-mode="props.fieldValidationMode"
    :default-display-instance-name="props.displayInstanceName"
    :on-submit="props.onSubmit"
    :on-validation="props.onValidation"
  >
    <FormitivaRenderer
      :definition="definition"
      :instance="resolvedInstance"
      :on-submit="onSubmit"
      :on-validation="onValidation"
    />
  </FormitivaProvider>
</template>
