// packages/vue/src/components/fields/ui-elements/Description.vue
<script setup lang="ts">
import { computed } from 'vue';
import useFormitivaContext from "../../../hooks/useFormitivaContext";
import { CSS_CLASSES } from '@formitiva/core';

interface DescriptionProps {
  field: {
    displayText?: string | string[]; // Can be a string or an array of strings for multiple lines
    textAlign?: "left" | "center" | "right";
    allowHtml?: boolean; // if true, displayText is treated as HTML and rendered with v-html
  };
}

const props = defineProps<DescriptionProps>();
const _ctx = useFormitivaContext();
const t = computed(() => _ctx.t);

const displayTextRaw = computed(() => props.field?.displayText ?? "");
const allowHtml = computed(() => Boolean(props.field?.allowHtml));
const align = computed(() => (props.field?.textAlign ?? "left") as "left" | "center" | "right");

const translated = computed(() => {
  const displayText = displayTextRaw.value;
  if (Array.isArray(displayText)) {
    const mapped = displayText.map((d) => t.value(d));
    return allowHtml.value ? mapped.join("") : mapped.join("\n");
  }
  return t.value(String(displayText));
});

const lines = computed<string[]>(() => {
  if (allowHtml.value) return [];
  const raw = translated.value.split(/\r\n|\r|\n/);
  return raw.map((line) => (line === "" ? "" : line.replace(/\t/g, "    ")));
});

const alignStyle = computed(() => ({ textAlign: align.value }));
</script>

<template>
  <div :class="CSS_CLASSES.description" v-if="allowHtml">
    <div :style="alignStyle" v-html="translated"></div>
  </div>
  <div :class="CSS_CLASSES.description" v-else>
    <div :style="alignStyle">
      <div v-for="(line, i) in lines" :key="i">
        <br v-if="line === ''" />
        <template v-else>{{ line }}</template>
      </div>
    </div>
  </div>
</template>

// packages/react/src/components/fields/ui-elements/Description.tsx
import * as React from "react";
import useFormitivaContext from "../../../hooks/useFormitivaContext";
import { CSS_CLASSES } from '@formitiva/core';

interface DescriptionProps {
  field: {
    displayText?: string | string[]; // Can be a string or an array of strings for multiple lines
    textAlign?: "left" | "center" | "right";
    allowHtml?: boolean; // if true, displayText is treated as HTML and rendered with dangerouslySetInnerHTML
  };
}

/**
 * Description component for displaying text content in forms
 * This is a UI-only component (not an input) used to show descriptive text
 * Similar to Image component, but for text display
 * 
 * @example
 * // JSON definition:
 * {
 *   "name": "welcomeMessage",
 *   "type": "description",
 *   "displayText": "Welcome to our form! Please fill out all required fields.",
 *   "textAlign": "center",
 *   "allowHtml": false
 * }
 */
const Description: React.FC<DescriptionProps> = ({ field }) => {
  const { t } = useFormitivaContext();
  
  const { displayText = "", textAlign = "left", allowHtml = false } = field;

  const translated = React.useMemo(() => {
    if (Array.isArray(displayText)) {
      const mapped = displayText.map((d) => t(d));
      return allowHtml ? mapped.join("") : mapped.join("\n");
    }
    return t(displayText as string);
  }, [t, displayText, allowHtml]);

  const lines = React.useMemo<string[]>(() => {
    if (allowHtml) return []; // If HTML is allowed, we won't split into lines since it will be rendered as HTML
    const raw = translated.split(/\r\n|\r|\n/);
    return raw.map((line) =>
      line === ""
        ? ""
        : line.replace(/\t/g, "\u00A0\u00A0\u00A0\u00A0").replace(/ /g, "\u00A0")
    );
  }, [translated, allowHtml]);

  if (allowHtml) {
    return (
      <div
        className={CSS_CLASSES.description}
        style={{ textAlign }}
        dangerouslySetInnerHTML={{ __html: translated }}
      />
    );
  }

  return (
    <div className={CSS_CLASSES.description} style={{ textAlign }}>
      {lines.map((line, i) => {
        if (line === "") return <div key={i}><br /></div>;
        return <div key={i}>{line}</div>;
      })}
    </div>
  );
};

Description.displayName = "Description";
export default React.memo(Description);
